"""
CXL Protocol Compliance Validator

Monitors simulation events and asserts CXL.mem semantic invariants.
Raises CXLProtocolError immediately if an invariant is violated.
"""

from typing import Optional
from src.core.packet import SimulationEvent, CXLPacket, CXLTransactionType

class CXLProtocolError(Exception):
    """Exception raised when a CXL protocol invariant is violated."""
    pass

class ProtocolValidator:
    """
    Hooks into SimulationEngine handlers to enforce protocol compliance.
    """
    
    def __init__(self, engine=None):
        self.engine = engine
        if engine:
            self.attach(engine)
            
    def attach(self, engine):
        """Attach to an engine's event handlers."""
        self.engine = engine
        engine.register_handler("host_generate", self.validate_host_generate)
        engine.register_handler("crossbar_process", self.validate_crossbar_process)
        
    def validate_host_generate(self, event: SimulationEvent):
        """Validate newly generated host requests."""
        if not event.packet:
            return
            
        packet = event.packet
        
        # Rule: Address must be 64-byte aligned
        if packet.address % 64 != 0:
            raise CXLProtocolError(f"Unaligned address 0x{packet.address:X} in packet {packet.packet_id}")
            
        # Rule: Size must be 64 bytes
        if packet.size != 64:
            raise CXLProtocolError(f"Invalid request size {packet.size} in packet {packet.packet_id}. Expected 64 bytes.")
            
    def validate_device_response(self, event: SimulationEvent):
        """Validate device responses before they are transmitted back."""
        # Device response events occur for each flit.
        # We only need to check the semantic rules when we have access to the packet.
        flit = event.flit
        if not flit or not flit.is_tail:
            return
            
        packet = flit.packet
        
        # Wait, the device generates a response packet AFTER processing the tail flit of a request.
        # We can hook into crossbar_process where the device injects the response.
        pass

    def validate_crossbar_process(self, event: SimulationEvent):
        """Validate response packets generated by device."""
        packet = event.packet
        if not packet or not packet.is_response:
            return
            
        if packet.tx_type == CXLTransactionType.MEM_READ_RESP:
            # MEM_READ_RESP must carry 64 bytes of data
            if packet.size != 64:
                raise CXLProtocolError(f"MEM_READ_RESP {packet.packet_id} has size {packet.size}, expected 64 bytes")
        elif packet.tx_type == CXLTransactionType.MEM_WRITE_ACK:
            # MEM_WRITE_ACK must have 0 bytes of data (just the header)
            if packet.size != 0:
                raise CXLProtocolError(f"MEM_WRITE_ACK {packet.packet_id} has size {packet.size}, expected 0 bytes")
